### ISSUE TITLE
fin dk a: b: c does not work properly in INSPIRE

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#699] opened 2014-04-30 15:41 UTC
Originally by *[valkyrie (@valkyriesavage)](https://github.com/valkyriesavage)* on 2011-06-22

as far as I can tell, the two sub-tasks here are

0) ensuring that the STISC is correctly emitting the terms searched for 
and
1) ensuring that INSPIRE's install is correctly indexing the keywords

**Comment by jirikuncar** [comment] 2015-04-22 18:41
@kaplun it looks like specific BibIndex problem. Has it been fixed in 1.x?

**Comment by kaplun** [comment] 2015-04-23 09:04
I assume nope.

**Comment by kaplun** [comment] 2015-04-23 09:04
It's sad to see so much work that has never be integrated. I guess it's too much of a pain as of today to integrate this. I will have a look.

**Comment by kaplun** [comment] 2015-04-23 09:13
I guess it's pointless today to try to integrate the work. However the branch comes with nice unit/regression tests. Maybe these could be ported to invenio_query_parser...

**Comment by kaplun** [comment] 2015-04-23 09:15
See: https://github.com/kaplun/invenio/tree/702-desy_keywords_particles

**Comment by kaplun** [comment] 2015-09-25 08:40
@Panos512 is investigating it with `invenio-query-parser`.

**Comment by kaplun** [comment] 2015-10-02 09:49
Moved to inveniosoftware/invenio-query-parser#38

**Closed by kaplun** 2015-10-02 09:49 UTC
Labels: c_BibIndex, in_triage, p_major, s_INSPIRE, t_bug
