### ISSUE TITLE
RFC deposit: filter depositions based on user roles

### ISSUE THREAD

**Issue by jmartinm** [inveniosoftware/invenio#2724] opened 2015-01-29 17:50 UTC
Problem
=======

Currently for all visitors of the index page of deposit ```/deposit``` all depositions are shown.

We would like to have some filtering done based on the roles of the current user so that different users can see different submissions.

Proposal
===========
https://github.com/inveniosoftware/invenio/blob/pu/invenio/modules/deposit/views/deposit.py#L113
```python
ctx = dict(
        deposition_types=DepositionType.all(),
        my_depositions=Deposition.get_depositions(current_user),
        prefill_data=draft_cache.data,
    )
```

Instead of ```DepositionType.all()``` we can have a new function ```DepositionType.all_authorized(current_user)``` that only returns deposition types the user is allowed to see.

We will need a new attribute in the ``DepositionType`` model that represents the roles that are authorized to see such Deposition type (we probably don't need a config variable for this, if a new role needs to be added to a deposition type, it can be changed in the DepositionType definition)

Then for all views that access a certain deposition type, like:

```python
@blueprint.route('/<depositions:deposition_type>')
@blueprint.route('/<depositions:deposition_type>/create',
                 methods=['POST', 'GET'])
@blueprint.route('/<depositions:deposition_type>/<int:uuid>/<draft_id>',
                 methods=['POST'])
```

There should be a protection so that, something like a 404 is returned if the user is not authorized. Should this be implemented as a decorator for those views?

What more should be taken into account? Suggestions for the implementation?

CC @lnielsen

**Comment by kaplun** [comment] 2015-01-29 19:40
What about using the native RBAC model of Invenio, hence instead of having Deposit connecteded to role we continue the current usage of the `submit` WebAccess action. It's probably not going to be as fast  as the proposed filter, but would be more consistent with the authorization model of Invenio.

Basically given the list of deposition types, you would display the deposition type `X` if the current user is authorized for the action `deposit` with `deposition_type=X`.

**Comment by jalavik** [comment] 2015-01-30 07:13
It would indeed be nice to connect this to the access module using parameterized authorizations.

**Comment by aw-bib** [comment] 2015-01-30 07:28
As a sidenote from our workflow at join2 it would indeed be _necessary_ to hide sumbissions in the first place. (All submissions are/have to be treated as visible for a given group only till further down the road they are approved to be public.) This would die if everyone could see all submissions. @kaplun our users are allowed to deposit every type, however, they are not allowed to see every submissions by others. (A submits a journal article to private collection a, B does so to b. A must not be allowed to see submissions from B.) If that's in your model I'd agree that consistency of the quite complex rules would be nice.

**Comment by lnielsen** [comment] 2015-01-30 10:11
I think this is a duplicate of #1946?

**Comment by jirikuncar** [comment] 2015-01-30 10:55
Taking https://github.com/inveniosoftware/invenio/issues/1946#issuecomment-50313526 and https://github.com/inveniosoftware/invenio/issues/2724#issuecomment-72089962 into account the solution seems to be:

- [ ] add `acl.py` with new `usedeposit` action
- [ ] `usedeposit` can accept `type` argument
- [ ] calculate `precached_allowed_deposition_types` when user visit `/deposit`
- [ ] "decorate" rest of deposit urls with decorator that consistently checks the access right

WDYT?

**Comment by jmartinm** [comment] 2015-01-30 11:08
That looks good to me. I will work on this end of next once I am back. Any more comments are welcome until then.

**Closed** 2015-05-29 08:51 UTC
Labels: c_deposit, master, RFC, t_enhancement
