### ISSUE TITLE
Allow to remove static formats from cache if they are no longer needed

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#1549] opened 2014-04-30 16:00 UTC
Originally by *arwagner* on 2013-07-01

It would be nice to have an bib-un-reformat like option to remove unnecessary bibformats from the db cache.

**Comment by tiborsimko** [comment] 2015-09-22 12:53
The issue is addressed in Invenio v2.0 via `inveniomanager`.  For Invenio v1.x, let's use the `dbexec` example as a workaround.

**Closed by tiborsimko** 2015-09-22 12:53 UTC
Labels: c_BibFormat, legacy, p_minor, t_enhancement
