### ISSUE TITLE
global: jinja2 friendlier console warnings

### ISSUE THREAD

**Issue by jmartinm** [inveniosoftware/invenio#2951] opened 2015-03-26 13:47 UTC
Since the introduction of https://github.com/inveniosoftware/invenio/commit/552d1c4cca765911f5df100abb862e8b39d8862f

the devserver console is full of messages like:

```python
/home/jmartinm/.virtualenvs/pu-inspire2/local/lib/python2.7/site-packages/jinja2/environment.py:966: RuntimeWarning: Convert string '/home/jmartinm/.virtualenvs/pu-inspire2/local/lib/python2.7/site-packages/jinja2/environment.py:966: RuntimeWarning: Convert string '.eJxtkNEKgjAUhl9lCd1J0QN0YbnoohJmEGEiyy064Ka4U-Tbl2Fzhpf_9_0czjmJF9MdXR_JrawVxxkIEsRdyED4P665ko5po3V5KVzXRuuENHkNFUKpnYpDnSkapcYMm2o4rce2q0DJ_6JltvUEA1coABun1kPbK7jB7FEJjtK9foAvesOifac-6bSljI6uPlmSqSHBIRxZ46siFlJGVmf3tZ6feChfOL-jKjx_kaZvaAWTqg.bqPhXDl7sl1Y16GkEl8OK5-4L5M' in template to unicode.
  return concat(self.root_render_func(self.new_context(vars)))
' in template to unicode.
  return concat(self.root_render_func(self.new_context(vars)))

/home/jmartinm/.virtualenvs/pu-inspire2/local/lib/python2.7/site-packages/jinja2/environment.py:966: RuntimeWarning: Convert string '/home/jmartinm/.virtualenvs/pu-inspire2/local/lib/python2.7/site-packages/jinja2/environment.py:966: RuntimeWarning: Convert string '0.00059700012207' in template to unicode.
  return concat(self.root_render_func(self.new_context(vars)))
' in template to unicode.
  return concat(self.root_render_func(self.new_context(vars)))

/home/jmartinm/.virtualenvs/pu-inspire2/local/lib/python2.7/site-packages/jinja2/environment.py:966: RuntimeWarning: Convert string '/home/jmartinm/.virtualenvs/pu-inspire2/local/lib/python2.7/site-packages/flask_debugtoolbar/templates/panels/sqlalchemy.html:31: RuntimeWarning: Convert string '<div class="highlight" style="background: #ffffff"><pre style="line-height: 125%"><span style="color: #008800; font-weight: bold">SELECT</span> format.id <span style="color: #008800; font-weight: bold">AS</span> format_id, format.name <span style="color: #008800; font-weight: bold">AS</span> format_name, format.code <span style="color: #008800; font-weight: bold">AS</span> format_code, format.description <span style="color: #008800; font-weight: bold">AS</span> format_description, format.content_type <span style="color: #008800; font-weight: bold">AS</span> format_content_type, format.mime_type <span style="color: #008800; font-weight: bold">AS</span> format_mime_type, format.visibility <span style="color: #008800; font-weight: bold">AS</span> format_visibility, format.last_updated <span style="color: #008800; font-weight: bold">AS</span> format_last_updated 
<span style="color: #008800; font-weight: bold">FROM</span> format 
<span style="color: #008800; font-weight: bold">WHERE</span> format.content_type <span style="color: #333333">!=</span> <span style="color: #333333">%</span>s <span style="color: #008800; font-weight: bold">AND</span> format.visibility <span style="color: #333333">=</span> <span style="color: #333333">%</span>s <span style="color: #008800; font-weight: bold">ORDER</span> <span style="color: #008800; font-weight: bold">BY</span> format.name
</pre></div>
' in template to unicode.
  <th>{% trans "Line" %}</th>
' in template to unicode.
  return concat(self.root_render_func(self.new_context(vars)))
```

I understand the unicode issue in the templates is worth fixing, but it:

1. Makes it difficult to work with, as all those messages are mixed up with messages you might be interested it while working on other features.

2. Don't seem helpful, as I don't see any pointer to the template that has the problem and what exactly the problem is. (well i know it is a unicode issue, but not exactly what to do about it)

So, can we either hide those messages or make them more explicit so that people that see them can actually fix the problem? I don't think in the current state they are going to have the desired effect.

**Comment by jalavik** [comment] 2015-03-26 14:53
Yeah, and in addition to several deprecation warnings, when loading search result pages, the console often crashes and reboots itself so you have to refresh a few times to load the page etc.

Can we redirect this output elsewhere or opt in for it?

**Comment by lnielsen** [comment] 2015-03-26 16:24
I think @jirikuncar is working on fixing the stack trace issue. 

``invenio.ext.jinja2hacks`` was initially a dirty temporary measure to be able to decode 8-bit string to unicode using utf8 instead of ascii. I know @jirikuncar have spent several days trying to fix ``jinja2hacks`` so that we could continue as normal, but the fact is that there's no easy solution. 

The reason that these warnings are loud is because they **will break** your production service and that they must be dealt with. I think we need all hands on deck to fix this issue and I'm aware it's interrupting existing work but travis builds is failing because of this so we are largely blind for integration as it is now.

To disable it simple remove the the ``warnings.warn`` from ``invenio.ext.jinja2hacks``.

The fix for the problem is quite simple: ``{{ var }}`` -> ``{{ var|u }}``

**Comment by jalavik** [comment] 2015-03-26 16:35
@lnielsen Thanks for the info. @jmartinm and I was discussing with @jirikuncar  and I got the understanding we could solve it also outside of the templates from the source of the variable - avoiding adding `| u` everywhere? Or will that just be about adding `unicode()` or  `str.decode` everywhere?

@jirikuncar also noticed that the flask toolbar produced several of these outputs, so disabling it with `DEBUG_TB_ENABLED=False` in the config helped locate the "real" issues.

**Comment by lnielsen** [comment] 2015-03-26 17:15
Yes, you're right it can also be fixed with ``s.decode('utf8')`` (which I think is about the same as ``{{ var|u }}``). I think I prefer ``{{ var|u }}`` over ``s.decode('utf8')``, but naturally the very best would be to ensure we deal with a unicode string in the first place (I think that's however a lot harder to fix).

**Comment by jirikuncar** [comment] 2015-03-26 20:31
@jmartinm you see from where the errors are coming e.g. `flask_debugtoolbar/templates/panels/sqlalchemy.html:31`. I think we can close this issue as we discussed it IRL.

**Closed by jirikuncar** 2015-03-26 20:31 UTC
Labels: t_enhancement
