### ISSUE TITLE
Problem with Docker installation

### ISSUE THREAD

**Issue by Pickeroll** [inveniosoftware/invenio#3737] opened 2016-12-20 09:58 UTC
Hi, I'm newbie here so excuse me in advance if I'm writing something wrong.

I'm trying to install invenio 3.0 with Docker following these instructions: 
http://invenio-software.org/gettingstarted? 

First of all I've replaced the git command with: `git clone https://github.com/inveniosoftware/invenio.git `, otherwhise this error will come out:

```
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.

```
And now that my invenio folder has been created I launched the `docker-compose build` command, this was the result:

`/bin/sh: 1: /tmp/provision-elasticsearch.sh: Permission denied
ERROR: Service 'elasticsearch' failed to build: The command '/bin/sh -c /tmp/provision-elasticsearch.sh' returned
zero code: 126`

I modified the elasticsearch script by adding chmod but the error was propagated to another script.
Can you please give me some advices ?

I'm running Docker on Windows10 and using powershell.

Thanks for your work.
Best regards.

**Comment by jacquerie** [comment] 2016-12-21 10:32
> First of all I've replaced the git command with: `git clone https://github.com/inveniosoftware/invenio.git `, otherwhise this error will come out:
> ```
> Permission denied (publickey).
> fatal: Could not read from remote repository.
> Please make sure you have the correct access rights
> and the repository exists.
> ```

This is because you didn't configure Git to use SSH. You can learn how to do that by reading GitHub's help pages on this topic: https://help.github.com/articles/generating-an-ssh-key/.

On the other hand, I believe that we should list the HTTPS link there, since it does not require the above setup and is the one recommended by GitHub.

**Comment by Pickeroll** [comment] 2016-12-22 14:10
> This is because you didn't configure GitHub to use SSH. You can learn how to do that by reading GitHub's help pages on this topic: https://help.github.com/articles/generating-an-ssh-key/.

>On the other hand, I believe that we should list the HTTPS link there, since it does not require the above setup and is the one recommended by GitHub.

First of all thanks for your reply.
The way that I used to download the repository can in someway afflict the correct behavior of the installation ?

By the way today I downloaded again the repo and now with the `docker-compose build` command I obtain:

`postgresql uses an image, skipping`
`redis uses an image, skipping`
`rabbitmq uses an image, skipping`
`Building elasticsearch`
`Traceback (most recent call last):`
 ` File "<string>", line 3, in <module>`
  `File "compose\cli\main.py", line 65, in main`
  `File "compose\cli\main.py", line 117, in perform_command`
  `File "compose\cli\main.py", line 223, in build`
 ` File "compose\project.py", line 300, in build`
 ` File "compose\service.py", line 742, in build`
  `File "site-packages\docker\api\build.py", line 105, in build`
  `File "site-packages\docker\utils\decorators.py", line 47, in inner`
  `File "site-packages\docker\client.py", line 135, in _post`
 ` File "site-packages\requests\sessions.py", line 522, in post`
  `File "site-packages\requests\sessions.py", line 475, in request`
  `File "site-packages\requests\sessions.py", line 596, in send`
  `File "site-packages\requests\adapters.py", line 423, in send`
  `File "site-packages\requests\packages\urllib3\connectionpool.py", line 595, in urlopen`
  `File "site-packages\requests\packages\urllib3\connectionpool.py", line 363, in _make_request`
  `File "httplib.py", line 1057, in request`
  `File "httplib.py", line 1097, in _send_request`
  `File "httplib.py", line 1053, in endheaders`
  `File "httplib.py", line 897, in _send_output`
  `File "httplib.py", line 859, in send`
  `File "site-packages\docker\transport\npipeconn.py", line 31, in connect`
  `File "site-packages\docker\transport\npipesocket.py", line 22, in wrapped`
 ` File "site-packages\docker\transport\npipesocket.py", line 49, in connect`
```
pywintypes.error: (2, 'WaitNamedPipe', 'The system cannot find the file specified.')
docker-compose returned -1`
```
I tried to download an older branch with the git option `--branch maint-1.1` but the result was the same.

**Comment by tiborsimko** [comment] 2017-01-09 11:18
@Pickeroll Is this still failing for you?  You can try something like

```console
$ cd /tmp
$ git clone https://github.com/inveniosoftware/invenio 
$ cd invenio 
$ docker-compose build --no-cache
$ docker-compose up -d 
$ docker-compose run --rm web ./scripts/populate-instance.sh 
$ firefox http://127.0.0.1/ 
$ firefox http://127.0.0.1/records/1
``` 

If it fails, perhaps it may be due to your using Docker on Windows? We are usually using various GNU/Linux and Mac OS environments only. You can perhaps try Windows + VirtualBox + Ubuntu and install Invenio using Docker inside the VM?

(Anyway, note that this installs Invenio 3.0 alpha version release series, so you shouldn't switch to `maint-1.1` branch, which is a maintenance branch for Invenio 1.1 release series...)

**Comment by martinkoehler** [comment] 2017-02-14 17:05
@Tibor: After having been able to successfully build invenio3 via docker some weeks ago, now 
`docker-compose build`
 fails while building 
`Building bundle: gen/styles.%(version)s.css`
during the setup of the web image.
The error was
`File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/invenio_assets/filters.py", line 98, in rebase_opt
    ['cleancss', '--version'], stdout=PIPE).communicate()
  File "/usr/local/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/local/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory`
For your convenience I attach the output of the docker-compose build --no-cache
[log.txt](https://github.com/inveniosoftware/invenio/files/774778/log.txt)


 I noticed that the python2.7. image was updated since my last successfull build.

I used 
   `docker-compose build --no-cache`
to ensure that I did not have a cache issue. 
As far as I could see the problem seems to be that cleancss is not correctly installed during the provisoning, but I might be wrong. (I even used earlier tags, but to no avail) Could you please confirm that a docker build from scratch does still work. Thanks
BTW: I'm using Debian Jessie as a docker host, 
Docker version 1.10.3, build 20f81dd
For invenio I'm on master 51ee6f8d87d554e31a5e86c17f2957e7d33b4ed8
Thanks for your help

**Comment by lnielsen** [comment] 2017-02-15 06:48
This is related to #3748 and because of recent clean css v4 release and probably you just need to change this line:
https://github.com/inveniosoftware/invenio/blob/master/scripts/provision-web.sh#L139
to
```
$sudo su -c "npm install -g node-sass@3.8.0 clean-css clean-css-cli requirejs uglify-js"
```
(i.e. adding ``clean-css-cli``)

**Comment by martinkoehler** [comment] 2017-02-15 08:31
@lnielsen Thanks: This fixes the error and the container builds. However, there is now a new error (Do not know whether this is critical)

Building bundle: gen/search.%(version)s.css
Failed, error was: cleancss: subprocess returned a non-success result code: 1, stdout=, stderr=
  error: unknown option `--root'
Building bundle: gen/i18n.%(version)s.js

**Comment by lnielsen** [comment] 2017-02-15 09:34
This is also related to clean-css :( Second try....pin to clean-css v3 :-) 

```
$sudo su -c "npm install -g node-sass@3.8.0 clean-css@3.4.19 requirejs uglify-js"
```

There must be some bundles which uses ``cleancss`` filter instead of ``cleancssurl`` that we'll have to sort out. We've also provided a fix to the webassets package which was merged and that will sort it, but it hasn't been released yet

**Comment by drjova** [comment] 2017-02-15 15:46
https://github.com/inveniosoftware/invenio-search-ui/pull/46

**Comment by tiborsimko** [comment] 2017-03-10 08:21
In order not to wait for upstream `webassets` release, we went for  `clean-css` pinning. 

All the installation issues have been fixed yesterday for all of Docker, Ubuntu14, CentOS7 supported platforms.  @Pickeroll @martinkoehler please just use the latest `master` branch:

```console
$ git clone https://github.com/inveniosoftware/invenio
$ cd invenio/
$ docker-compose build
$ docker-compose up
$ docker-compose run --rm web ./scripts/populate-instance.sh
$ firefox http://127.0.0.1/records/1
```

**Closed** 2017-03-10 08:21 UTC
Labels: Component: installation, Type: discussion

**Comment by martinkoehler** [comment] 2017-03-10 10:34
Dear Tibor,
thanks a lot. I can confirm that it now works with a fresh docker installation.
