### ISSUE TITLE
bibdocfile cli query optimization

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#1583] opened 2014-04-30 16:00 UTC
Originally by _[Thorsten (@tsgit)](https://github.com/tsgit)_ on 2013-09-11

on the Inspire production system (which is maint-1.1 at the time of writing) with > 1 million records in the db this command

$ bibdocfile --hard-delete -d 1454806  --with-format=pdf --with-version=1

takes several minutes and the mysql processlist shows multiple expensive table joins like this

 1057154 | inspirehep | pcudssw1504.cern.ch:52485 | inspirehep | Query
  |    0 | Creating tmp table   | SELECT bx.value FROM bib98x AS bx,
bibrec_bib98x AS bibx WHERE bibx.id_bibrec IN (1085831) AND bx.id
......

The equivalent command

$ bibdocfile --hard-delete -r 351327 --with-format=pdf --with-version=1

using recid instead of docid completes quickly. Looks like a simple query optimization could be done in the former case.

Cheers
Thorsten

**Comment by kaplun** [comment] 2017-01-05 12:43
I can't reproduce this nowadays. Maybe better DB? I think we can safely close it.

**Closed by kaplun** 2017-01-05 12:43 UTC
Labels: Component: BibDocFile, Component: global, Type: enhancement
