### ISSUE TITLE
search: putting whole query into parentheses results in empty result

### ISSUE THREAD

**Issue by invenio-developers** [inveniosoftware/invenio#1791] opened 2014-06-08 17:44 UTC
<a href="https://github.com/kneczaj"><img src="https://avatars.githubusercontent.com/u/4245137?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kneczaj](https://github.com/kneczaj)**
_Tuesday Apr 15, 2014 at 14:21 GMT_
_Originally opened as https://github.com/jirikuncar/invenio/issues/192_

----

When the whole query is in parentheses the result is empty:

For e.g. 'collection:"Multimedia & Arts"' works whereas '(collection:"Multimedia & Arts")' gives empty result.

The issue is quite old - on old official inspirehep.net page the bug exists too.

**Comment by tiborsimko** [comment] 2015-09-21 15:01
The issue is addressed by https://github.com/inveniosoftware/invenio-query-parser

**Closed by tiborsimko** 2015-09-21 15:01 UTC
Labels: c_WebSearch, master, p_minor, t_bug
